{% set version = "2020.4" %}

package:
  name: pytz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytz/pytz-{{ version }}.tar.gz
  sha256: 3e6b7dd2d1e0a59084bcee14a17af60c5c562cdc16d828e8eba2e683d3a7e268

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pytz
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pythonhosted.org/pytz/
  license: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical.
  description: |
    pytz brings the Olson tz database into Python. This library allows
    accurate and cross platform timezone calculations using Python 2.4 or
    higher. It also solves the issue of ambiguous times at the end of daylight
    saving time.
  doc_url: http://pythonhosted.org/pytz/
  dev_url: https://github.com/newvem/pytz

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
