travis:
  secure:
    BINSTAR_TOKEN: gggyL2Pq8Okfy7J//smfbPoLIMKok5lqubnme9tZp379xL5GRUk6CjDRpDmIrdcSMCIwmdepTizPJzvUs95aBDkN9pZPS218PVqkNWaBWgUe5aLZRIQPx4xUd8P7oZEwjNRB7F6EaP58yeDgX46iJAfQ6NJyRCwPWIM0Fy+4cSkQb3AizDkSOAJ0XFjO5VW5T6qfM+oh0SDjSn5BXrI3f2oLN6W/S7j2gkNNxjU+WkpY6S7wWhxuorTP4e0Hz5zLx1Rj2qiflgIIdvOcySJiO/5Otx4nJAEC2ExPU2cE1O9meDNklRjRQCFTJmt+CjySXInflNKRzuqifGlIqRSuEdg6rqdIlLvaxlp3Y089EEygJblUaq9C+8kj18OTO4TlfVnOw4Ir7qqHjMx+7Q78xNFklF7xhN2assa+RNrSgZC+9pw9//3jmjT5uFdOdxeqEbX3t5K8/3ZWO0pX+/0VbsfdDgQKyx6v25qFdSXnSUqsIBHb3Dm2gkdDnbMZAT0BJDnJO+4L6i8C6dHHBfZ9Zn84izV1btZTeEGKCnBnh+3palZph87xNjmUJkIezrXKMNNw3vPUYLX723TWTWdA3oVKwJor2s6I1IUjge2W8kF6wcnmj9wFQMufF2pNKRB+cNWEBY42lMoIIz02MZVeQtINNbpu0JKOsPfPn61HqPw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
